<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>predictive risk </name>
  <uuid>1d70ae57-025f-4d66-9dde-d5551bac8c55</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to the machine learning scoreboard computed from 
	Industry being Industry , 
	ClientInformation being Client ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
