<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>default-rule</name>
  <uuid>fbe2abec-7109-4a22-b90d-bebed29237c4</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[add a new ML model output where
		the confidence is 0 , 
		the weight is 0 , 
		the rank is 0 to decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
