<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>get machine learning output</name>
  <uuid>7514ce9e-2d62-4648-8e3d-60e38f2995cf</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if the predicted clientdefaultedpayment is "TRUE"
then
set decision to a new Scoreboard where
		the Confidence is the confidence , 
		High risk is true, 
		the Segment is "Unknown" ;
else 
set decision to a new Scoreboard where
		the Confidence is the confidence , 
		High risk is false, 
		the Segment is "Unknown" ;
]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
